assert(SMODS.load_file("consumables/consumables.lua"))()
assert(SMODS.load_file("enhancements/enhancements.lua"))()
assert(SMODS.load_file("hooks/hooks.lua"))()
assert(SMODS.load_file("icon.lua"))()
assert(SMODS.load_file("jokers/jokers.lua"))()
